/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2014 VigLink. Rights reserved and patent(s) pending.
*/
(function(l){var f,b={_breaker:{},each:function(a,c){var d,e;if("object"===b.type(a)&&a.hasOwnProperty)for(d in a){if(a.hasOwnProperty(d)&&c(a[d],d)===b._breaker)break}else if(a){d=0;for(e=a.length;d<e&&c(a[d],d)!==b._breaker;d++);}},extend:function(a){var c,d,b,g,h=arguments.length;a=a||{};for(d=1;d<h;d++)if(g=arguments[d],void 0!==g&&null!==g)for(b in g)c=g[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(){var a=function(a,d){try{return("function"===typeof window[d]||"object"===
typeof window[d])&&a instanceof window[d]}catch(b){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in c)?"document":c==c.window?"window":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},
attrValues:function(a,c,d){return(c=a[c])?c.split(d||" "):[]},batchable:function(a){a=b.extend({batch:b.noop,single:b.noop,timeout:100},a);var c=[],d=b.traits.cors&&b.traits.json,e=null,g=function(){null!==e&&(clearTimeout(e),e=null);1===c.length?a.single.apply(this,c[0]):1<c.length&&a.batch(c);c=[]},h=function(){c.push(b.toArray(arguments));null===e&&(e=setTimeout(b.bind(function(){g()},this),a.timeout))};b.extend(h,{flush:g,now:a.single});return d?h:a.single},bind:function(a,c){return function(){return a.apply(c,
arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),d=0;return function(b,g,h){if(b){var m=b[c];if(m||void 0!==h)return m||(m=++d),a[m]||(b[c]=m,a[m]={}),void 0!==h&&(a[m][g]=h),"string"===typeof g?a[m][g]:a[m]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=b.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return b.extend({},a)},contains:function(a,c){return-1!==b.indexOf(a,c)},context:function(a){"element"===
b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a,c){for(var d=a.self;d.parent&&d.parent!==d;)if(d=d.parent,d===c)return!0;return!1},cors:function(a,c,d){var b,g=function(){d?d(b.responseText):eval(b.responseText)};b=new window.XMLHttpRequest;b.onreadystatechange=function(){4===b.readyState&&200===
b.status&&g()};try{return b.open("POST",a),b.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),b.withCredentials=!0,b.send(c),!0}catch(h){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,d,e){var g;a=(e||document).createElement(a);c=c||{};d=d||{};for(g in c)void 0!==c[g]&&(a[g]=c[g]);b.css(a,d);return a},css:function(a,c){for(var d in c)try{a.style[d]=c[d]}catch(b){}return a},destructing:function(a){return function(a){var b=!1,e;return function(){b||
(e=a.apply(null,arguments),b=!0);return e}}(a)},escapeRegExp:function(){var a;return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(e){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},exceptionLogger:function(){var a=!1,c=b.noop;return function(b,e){if(void 0!==e)a=e,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(e){c(e)}else return b.apply(this,
arguments)}}}(),find:function(a,c){var d;b.each(a,function(a,g){if(c(a,g))return d=a,b._breaker});return d},generateNodeFilter:function(){var a=function(a,b){var g,h;b=","+b.join(",")+",";g=0;for(h=a.length;g<h;g++)if(c(a[g],b))return!0;return!1},c=function(a,c){return-1!==c.indexOf(","+a+",")};return function(d){d=b.extend({custom:null,classes:[],rels:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");return function(e,g){g=b.extend({ancestors:!0,self:!0},g);var h=!0,m=
!0,f=function(e,g){var h;if(h=!(d.tags.length&&c(e.nodeName.toLowerCase(),d.tags))){if(h=d.classes.length){h=d.classes;var m=b.attrValues(e,"className");h=a(h,m)}if(h=!h){if(h=d.rels.length)h=d.rels,m=b.attrValues(e,"rel"),h=c(e.nodeName.toLowerCase(),",a,")&&a(h,m);h=!h&&!("function"===b.type(d.custom)&&d.custom(e,g))}}return h},m=!g.self||f(e,!0);if(g.ancestors)for(;e.parentNode;)if(e=e.parentNode,1===e.nodeType&&!f(e,!1)){h=!1;break}return m&&h}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},
fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,d=Infinity,e=Infinity,g=-Infinity,h=-Infinity,m;for(a=0;a<c;a++)m=b.position(arguments[a]),d=Math.min(d,m.x),e=Math.min(e,m.y),g=Math.max(g,m.x+arguments[a].offsetWidth),h=Math.max(h,m.y+arguments[a].offsetHeight);return{x:d,y:e,w:g-d,h:h-e,x1:d,y1:e,x2:g,y2:h}},getActualHref:function(a){return b.cache(a,
"href")||a.href},hasAttrValue:function(a,c,d,e){return c?b.contains(b.attrValues(a,c,e),d):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},indexOf:function(){return Array.prototype.indexOf?function(a,c){return Array.prototype.indexOf.call(a,c)}:function(a,c){var b,e;b=0;for(e=a.length;b<e;b++)if(a[b]===c)return b;return-1}}(),isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&
a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var c=document.getElementsByTagName("script")[0];a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c){var d=[];b.each(a,function(a,b){void 0!==a&&(d[b]=c(a))});return d},matches:function(){try{return this.Sizzle.matchesSelector.apply(this.Sizzle,arguments)}catch(a){return!0}},on:function(){var a;return function(c,d,e){var g,h;if(1===arguments.length)a=c;else{if(2===
arguments.length){if(!a)return;e=d;d=c;c=a}try{g=c["on"+d]}catch(m){}"function"===typeof g&&(c["on"+d]=b.bind(function(a){a=a||window.event;var d=g.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));h=b.exceptionLogger(function(){if(a.enabled())return e.apply(null,arguments)});c.addEventListener?c.addEventListener(d,h,!1):c.attachEvent&&
c.attachEvent("on"+d,h)}}}(),position:function(a,c){var b,e=0,g=0,h=0,m=0;c=c||document;if(!a.offsetParent)return!1;b=a;do e+=b.offsetLeft,g+=b.offsetTop,b=b.offsetParent;while(b);b=a;do h+=b.scrollLeft,m+=b.scrollTop,b=b.parentNode;while(b&&b!==c.body);return{x:e-h,y:g-m}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(b,d){(null===b||void 0===b)&&delete a[d]});return a},ready:function(){var a=!1,c=[],d=!1,e,g,h,m,f;document.addEventListener?
h=function(){document.removeEventListener("DOMContentLoaded",h,!1);f()}:document.attachEvent&&(m=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",m),f())});e=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return f();if(document.addEventListener)document.addEventListener("DOMContentLoaded",h,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",m);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&
c&&g()}b.on(window,"load",f)}};g=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.exceptionLogger(g),1);return}f()}};f=function(){if(!d){if(!document.body)return setTimeout(b.exceptionLogger(f),13);d=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){e();d?a():c.push(a)}}(),reformatKeys:function(a){var c,d,e=function(a){return"_"+a.toLowerCase()};for(c in a)d=c.replace(/([A-Z])/g,e),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),d!==c&&(a[d]=
a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var d,e,g=b.attrValues(a,"className");d=0;for(e=g.length;d<e;d++)g[d]===c&&delete g[d];a.className=g.join(" ")}},request:function(a,c,d){var e,g;d=b.extend({fn:b.noop,jsonp:!0,"return":!1,timeout:null},d);"string"===typeof d.fn?(e=window[d.fn],g=d.fn):"function"===typeof d.fn&&(!0!==d.jsonp?e=d.fn:(e=b.destructing(d.fn),g=b.uniqid("vglnk_jsonp_"),window[g]=b.exceptionLogger(function(){e.apply(this,arguments);window[g]=void 0}),
null!==d.timeout&&setTimeout(b.exceptionLogger(e),d.timeout)));g&&(c=b.extend({format:"jsonp",jsonp:g},c));c=b.toQuery(c);return d["return"]?a+(c.length?"?":"")+c:b.traits.cors&&b.cors(a,c,d.jsonp?null:e)?!0:b.jsonp(a+(c.length?"?":"")+c)},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(b){var d,e,g=[];d=0;for(e=a.length;d<e;d++)g[d]=a[d];return g}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},
toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},transmitsPII:function(a){return b.containsPII(a+" "+document.referrer)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}()});var r=function(){var a=b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};r.amd=!0;(function(a){function b(a,
c,d,e){var h,g,m,f,k;(c?c.ownerDocument||c:E)!==A&&I(c);c=c||A;d=d||[];if(!a||"string"!==typeof a)return d;if(1!==(f=c.nodeType)&&9!==f)return[];if(F&&!e){if(h=ta.exec(a))if(m=h[1])if(9===f)if((g=c.getElementById(m))&&g.parentNode){if(g.id===m)return d.push(g),d}else return d;else{if(c.ownerDocument&&(g=c.ownerDocument.getElementById(m))&&U(c,g)&&g.id===m)return d.push(g),d}else{if(h[2])return J.apply(d,c.getElementsByTagName(a)),d;if((m=h[3])&&v.getElementsByClassName&&c.getElementsByClassName)return J.apply(d,
c.getElementsByClassName(m)),d}if(v.qsa&&(!y||!y.test(a))){g=h=x;m=c;k=9===f&&a;if(1===f&&"object"!==c.nodeName.toLowerCase()){f=u(a);(h=c.getAttribute("id"))?g=h.replace(ua,"\\$&"):c.setAttribute("id",g);g="[id='"+g+"'] ";for(m=f.length;m--;)f[m]=g+O(f[m]);m=ea.test(a)&&p(c.parentNode)||c;k=f.join(",")}if(k)try{return J.apply(d,m.querySelectorAll(k)),d}catch(l){}finally{h||c.removeAttribute("id")}}}var n;a:{a=a.replace(X,"$1");g=u(a);if(!e&&1===g.length){h=g[0]=g[0].slice(0);if(2<h.length&&"ID"===
(n=h[0]).type&&v.getById&&9===c.nodeType&&F&&q.relative[h[1].type]){c=(q.find.ID(n.matches[0].replace(K,L),c)||[])[0];if(!c){n=d;break a}a=a.slice(h.shift().value.length)}for(f=Y.needsContext.test(a)?0:h.length;f--;){n=h[f];if(q.relative[m=n.type])break;if(m=q.find[m])if(e=m(n.matches[0].replace(K,L),ea.test(h[0].type)&&p(c.parentNode)||c)){h.splice(f,1);a=e.length&&O(h);if(!a){J.apply(d,e);n=d;break a}break}}}fa(a,g)(e,c,!F,d,ea.test(a)&&p(c.parentNode)||c);n=d}return n}function d(){function a(c,
d){b.push(c+" ")>q.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function e(a){a[x]=!0;return a}function g(a){var b=A.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function h(a,b){for(var c=a.split("|"),d=a.length;d--;)q.attrHandle[c[d]]=b}function m(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||la)-(~a.sourceIndex||la);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}
function f(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function k(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function l(a){return e(function(b){b=+b;return e(function(c,d){for(var e,h=a([],c.length,b),g=h.length;g--;)if(c[e=h[g]])c[e]=!(d[e]=c[e])})})}function p(a){return a&&typeof a.getElementsByTagName!==R&&a}function t(){}function u(a,d){var e,h,g,m,f,k,n;if(f=ma[a+" "])return d?0:f.slice(0);f=a;k=[];for(n=
q.preFilter;f;){if(!e||(h=va.exec(f)))h&&(f=f.slice(h[0].length)||f),k.push(g=[]);e=!1;if(h=wa.exec(f))e=h.shift(),g.push({value:e,type:h[0].replace(X," ")}),f=f.slice(e.length);for(m in q.filter)if((h=Y[m].exec(f))&&(!n[m]||(h=n[m](h))))e=h.shift(),g.push({value:e,type:m,matches:h}),f=f.slice(e.length);if(!e)break}return d?f.length:f?b.error(a):ma(a,k).slice(0)}function O(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function s(a,b,c){var d=b.dir,e=c&&"parentNode"===d,h=xa++;return b.first?
function(b,c,h){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,h)}:function(b,c,da){var g,D,m,f=G+" "+h;if(da)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,da))return!0}else for(;b=b[d];)if(1===b.nodeType||e)if(m=b[x]||(b[x]={}),(D=m[d])&&D[0]===f){if(!0===(g=D[1])||g===Z)return!0===g}else if(D=m[d]=[f],D[1]=a(b,c,da)||Z,!0===D[1])return!0}}function ga(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function $(a,b,c,d,e){for(var h,g=[],m=0,f=a.length,
k=null!=b;m<f;m++)if(h=a[m])if(!c||c(h,d,e))g.push(h),k&&b.push(m);return g}function ha(a,d,h,g,m,f){g&&!g[x]&&(g=ha(g));m&&!m[x]&&(m=ha(m,f));return e(function(e,f,k,n){var l,t,p=[],B=[],z=f.length,w;if(!(w=e)){w=d||"*";for(var q=k.nodeType?[k]:k,C=[],u=0,v=q.length;u<v;u++)b(w,q[u],C);w=C}w=a&&(e||!d)?$(w,p,a,k,n):w;q=h?m||(e?a:z||g)?[]:f:w;h&&h(w,q,k,n);if(g){l=$(q,B);g(l,[],k,n);for(k=l.length;k--;)if(t=l[k])q[B[k]]=!(w[B[k]]=t)}if(e){if(m||a){if(m){l=[];for(k=q.length;k--;)if(t=q[k])l.push(w[k]=
t);m(null,q=[],l,n)}for(k=q.length;k--;)if((t=q[k])&&-1<(l=m?P.call(e,t):p[k]))e[l]=!(f[l]=t)}}else q=$(q===f?q.splice(z,q.length):q),m?m(null,f,q,n):J.apply(f,q)})}function ia(a){var b,c,d,e=a.length,h=q.relative[a[0].type];c=h||q.relative[" "];for(var g=h?1:0,m=s(function(a){return a===b},c,!0),f=s(function(a){return-1<P.call(b,a)},c,!0),k=[function(a,c,d){return!h&&(d||c!==aa)||((b=c).nodeType?m(a,c,d):f(a,c,d))}];g<e;g++)if(c=q.relative[a[g].type])k=[s(ga(k),c)];else{c=q.filter[a[g].type].apply(null,
a[g].matches);if(c[x]){for(d=++g;d<e&&!q.relative[a[d].type];d++);return ha(1<g&&ga(k),1<g&&O(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(X,"$1"),c,g<d&&ia(a.slice(g,d)),d<e&&ia(a=a.slice(d)),d<e&&O(a))}k.push(c)}return ga(k)}function ya(a,d){var h=0,g=0<d.length,m=0<a.length,f=function(e,f,k,n,l){var t,p,B,z=0,w="0",u=e&&[],C=[],v=aa,s=e||m&&q.find.TAG("*",l),O=G+=null==v?1:Math.random()||0.1,y=s.length;l&&(aa=f!==A&&f,Z=h);for(;w!==y&&null!=(t=s[w]);w++){if(m&&t){for(p=0;B=
a[p++];)if(B(t,f,k)){n.push(t);break}l&&(G=O,Z=++h)}g&&((t=!B&&t)&&z--,e&&u.push(t))}z+=w;if(g&&w!==z){for(p=0;B=d[p++];)B(u,C,f,k);if(e){if(0<z)for(;w--;)!u[w]&&!C[w]&&(C[w]=za.call(n));C=$(C)}J.apply(n,C);l&&(!e&&0<C.length&&1<z+d.length)&&b.uniqueSort(n)}l&&(G=O,aa=v);return u};return g?e(f):f}var S,v,Z,q,ba,na,fa,aa,M,T,I,A,H,F,y,Q,ca,U,x="sizzle"+-new Date,E=a.document,G=0,xa=0,oa=d(),ma=d(),pa=d(),ja=function(a,b){a===b&&(T=!0);return 0},R="undefined",la=-2147483648,Aa={}.hasOwnProperty,N=[],
za=N.pop,Ba=N.push,J=N.push,qa=N.slice,P=N.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},ra="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),sa="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+ra+")|)|)[\\x20\\t\\r\\n\\f]*\\]",ka=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+sa.replace(3,8)+")*)|.*)\\)|)",
X=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,va=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,wa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Ca=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Da=RegExp(ka),Ea=RegExp("^"+ra+"$"),Y={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+sa),PSEUDO:RegExp("^"+ka),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")},Fa=/^(?:input|select|textarea|button)$/i,Ga=/^h\d$/i,V=/^[^{]+\{\s*\[native \w/,ta=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ea=/[+~]/,ua=/'|\\/g,K=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,
L=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{J.apply(N=qa.call(E.childNodes),E.childNodes),N[E.childNodes.length].nodeType}catch(Ha){J={apply:N.length?function(a,b){Ba.apply(a,qa.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}v=b.support={};na=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};I=b.setDocument=function(a){var b=a?a.ownerDocument||
a:E;a=b.defaultView;if(b===A||9!==b.nodeType||!b.documentElement)return A;A=b;H=b.documentElement;F=!na(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){I()},!1):a.attachEvent&&a.attachEvent("onunload",function(){I()}));v.attributes=g(function(a){a.className="i";return!a.getAttribute("className")});v.getElementsByTagName=g(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});v.getElementsByClassName=V.test(b.getElementsByClassName)&&
g(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});v.getById=g(function(a){H.appendChild(a).id=x;return!b.getElementsByName||!b.getElementsByName(x).length});v.getById?(q.find.ID=function(a,b){if(typeof b.getElementById!==R&&F){var c=b.getElementById(a);return c&&c.parentNode?[c]:[]}},q.filter.ID=function(a){var b=a.replace(K,L);return function(a){return a.getAttribute("id")===b}}):(delete q.find.ID,
q.filter.ID=function(a){var b=a.replace(K,L);return function(a){return(a=typeof a.getAttributeNode!==R&&a.getAttributeNode("id"))&&a.value===b}});q.find.TAG=v.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==R)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],e=0,h=b.getElementsByTagName(a);if("*"===a){for(;c=h[e++];)1===c.nodeType&&d.push(c);return d}return h};q.find.CLASS=v.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==R&&F)return b.getElementsByClassName(a)};
Q=[];y=[];if(v.qsa=V.test(b.querySelectorAll))g(function(a){a.innerHTML="<select t=''><option selected=''></option></select>";a.querySelectorAll("[t^='']").length&&y.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||y.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||y.push(":checked")}),g(function(a){var c=b.createElement("input");
c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&y.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||y.push(":enabled",":disabled");a.querySelectorAll("*,:x");y.push(",.*:")});(v.matchesSelector=V.test(ca=H.webkitMatchesSelector||H.mozMatchesSelector||H.oMatchesSelector||H.msMatchesSelector))&&g(function(a){v.disconnectedMatch=ca.call(a,"div");ca.call(a,"[s!='']:x");Q.push("!=",ka)});y=y.length&&RegExp(y.join("|"));
Q=Q.length&&RegExp(Q.join("|"));U=(a=V.test(H.compareDocumentPosition))||V.test(H.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};ja=a?function(a,c){if(a===c)return T=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===
(c.ownerDocument||c)?a.compareDocumentPosition(c):1;return d&1||!v.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===E&&U(E,a)?-1:c===b||c.ownerDocument===E&&U(E,c)?1:M?P.call(M,a)-P.call(M,c):0:d&4?-1:1}:function(a,c){if(a===c)return T=!0,0;var d,e=0;d=a.parentNode;var h=c.parentNode,g=[a],W=[c];if(!d||!h)return a===b?-1:c===b?1:d?-1:h?1:M?P.call(M,a)-P.call(M,c):0;if(d===h)return m(a,c);for(d=a;d=d.parentNode;)g.unshift(d);for(d=c;d=d.parentNode;)W.unshift(d);for(;g[e]===W[e];)e++;
return e?m(g[e],W[e]):g[e]===E?-1:W[e]===E?1:0};return b};b.matches=function(a,d){return b(a,null,null,d)};b.matchesSelector=function(a,d){(a.ownerDocument||a)!==A&&I(a);d=d.replace(Ca,"='$1']");if(v.matchesSelector&&F&&(!Q||!Q.test(d))&&(!y||!y.test(d)))try{var e=ca.call(a,d);if(e||v.disconnectedMatch||a.document&&11!==a.document.nodeType)return e}catch(h){}return 0<b(d,A,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==A&&I(a);return U(a,b)};b.attr=function(a,b){(a.ownerDocument||
a)!==A&&I(a);var c=q.attrHandle[b.toLowerCase()],c=c&&Aa.call(q.attrHandle,b.toLowerCase())?c(a,b,!F):void 0;return void 0!==c?c:v.attributes||!F?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;T=!v.detectDuplicates;M=!v.sortStable&&a.slice(0);a.sort(ja);if(T){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}M=null;return a};ba=b.getText=
function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=ba(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=ba(b);return c};q=b.selectors={cacheLength:50,createPseudo:e,match:Y,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(K,
L);a[3]=(a[4]||a[5]||"").replace(K,L);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[5]&&a[2];if(Y.CHILD.test(a[0]))return null;if(a[3]&&void 0!==a[4])a[2]=a[4];else if(c&&Da.test(c)&&(b=u(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,
b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(K,L).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=oa[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&oa(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==R&&a.getAttribute("class")||"")})},ATTR:function(a,d,e){return function(h){h=b.attr(h,a);if(null==
h)return"!="===d;if(!d)return!0;h+="";return"="===d?h===e:"!="===d?h!==e:"^="===d?e&&0===h.indexOf(e):"*="===d?e&&-1<h.indexOf(e):"$="===d?e&&h.slice(-e.length)===e:"~="===d?-1<(" "+h+" ").indexOf(e):"|="===d?h===e||h.slice(0,e.length+1)===e+"-":!1}},CHILD:function(a,b,c,d,e){var h="nth"!==a.slice(0,3),g="last"!==a.slice(-4),m="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,f){var k,n,l,t,D;c=h!==g?"nextSibling":"previousSibling";var p=b.parentNode,B=m&&b.nodeName.toLowerCase();
f=!f&&!m;if(p){if(h){for(;c;){for(n=b;n=n[c];)if(m?n.nodeName.toLowerCase()===B:1===n.nodeType)return!1;D=c="only"===a&&!D&&"nextSibling"}return!0}D=[g?p.firstChild:p.lastChild];if(g&&f){f=p[x]||(p[x]={});k=f[a]||[];t=k[0]===G&&k[1];l=k[0]===G&&k[2];for(n=t&&p.childNodes[t];n=++t&&n&&n[c]||(l=t=0)||D.pop();)if(1===n.nodeType&&++l&&n===b){f[a]=[G,t,l];break}}else if(f&&(k=(b[x]||(b[x]={}))[a])&&k[0]===G)l=k[1];else for(;n=++t&&n&&n[c]||(l=t=0)||D.pop();)if((m?n.nodeName.toLowerCase()===B:1===n.nodeType)&&
++l)if(f&&((n[x]||(n[x]={}))[a]=[G,l]),n===b)break;l-=e;return l===d||0===l%d&&0<=l/d}}},PSEUDO:function(a,d){var h,g=q.pseudos[a]||q.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return g[x]?g(d):1<g.length?(h=[a,a,"",d],q.setFilters.hasOwnProperty(a.toLowerCase())?e(function(a,b){for(var c,e=g(a,d),h=e.length;h--;)c=P.call(a,e[h]),a[c]=!(b[c]=e[h])}):function(a){return g(a,0,h)}):g}},pseudos:{not:e(function(a){var b=[],c=[],d=fa(a.replace(X,"$1"));return d[x]?e(function(a,b,c,e){e=
d(a,null,e,[]);for(var h=a.length;h--;)if(c=e[h])a[h]=!(b[h]=c)}):function(a,e,h){b[0]=a;d(b,null,h,c);return!c.pop()}}),has:e(function(a){return function(d){return 0<b(a,d).length}}),contains:e(function(a){return function(b){return-1<(b.textContent||b.innerText||ba(b)).indexOf(a)}}),lang:e(function(a){Ea.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(K,L).toLowerCase();return function(b){var c;do if(c=F?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),
c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===H},focus:function(a){return a===A.activeElement&&(!A.hasFocus||A.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},
selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!q.pseudos.empty(a)},header:function(a){return Ga.test(a.nodeName)},input:function(a){return Fa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==
(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:l(function(){return[0]}),last:l(function(a,b){return[b-1]}),eq:l(function(a,b,c){return[0>c?c+b:c]}),even:l(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:l(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:l(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:l(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};q.pseudos.nth=q.pseudos.eq;for(S in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})q.pseudos[S]=
f(S);for(S in{submit:!0,reset:!0})q.pseudos[S]=k(S);t.prototype=q.filters=q.pseudos;q.setFilters=new t;fa=b.compile=function(a,b){var c,d=[],e=[],h=pa[a+" "];if(!h){b||(b=u(a));for(c=b.length;c--;)h=ia(b[c]),h[x]?d.push(h):e.push(h);h=pa(a,ya(e,d))}return h};v.sortStable=x.split("").sort(ja).join("")===x;v.detectDuplicates=!!T;I();v.sortDetached=g(function(a){return a.compareDocumentPosition(A.createElement("div"))&1});g(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||
h("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!v.attributes||!g(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&h("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});g(function(a){return null==a.getAttribute("disabled")})||h("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});"function"===typeof r&&r.amd?r(function(){return b}):"undefined"!==typeof module&&module.exports?module.exports=b:a.Sizzle=b})(window);b.browser=function(){var a,c={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(d,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.platforms=function(){var a={bbp:{id_finder:["div",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content,.postbody .signature"},
ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^='body'],.post_inner .signature"},vb3:{id_finder:["div[id], table[id]",/^post(\d+)$/],scope:"td[id^='td_post_'] div[id^='post_message_'],td[id^='td_post_'] div[id^='post_message_'] ~ div:not([class])"},vb4:{id_finder:["li",/^post_(\d+)$/],scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}};return function(c){return b.extend(a[c]||{},
{getPostIDs:function(){var a=[],c=this.id_finder;c&&b.each(b.select(c[0]),function(b){var h=c[2]||"id";(b=b[h]?b[h].match(c[1]):null)&&a.push(b[1])});return a.length?a:null}})}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||
!(b.browser.ie||b.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var k,p,s;f={PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",api:function(){var a=function(a,c,g){g=g||{};c=b.extend(f.commonParams(a),c);c.subId&&c.key!==k.key&&(c.subId=null);return{method:a,opts:g,params:c}},c=function(a){return b.request(k.api_url+"/"+a.method,a.params,a.opts)};return b.batchable({batch:function(){var d=function(a,c){a=b.fromJSON(a)||{};b.each(a,function(a,d){var e,
f=c[d];a&&f&&("domains"===d&&"array"===b.type(a)&&(a={results:a}),a="string"===b.type(a)&&(e=a.match(/^\s*\w+\((.*)\);?\s*$/))?b.fromJSON("["+e[1]+"]")||{}:[a],f.apply(window,a))})};return function(e){var g={},h={};b.each(e,function(c){c=a.apply(this,c);h[c.method]=c.opts.fn||b.noop;g[c.method]=b.prune(c.params)});c({method:"batch",params:b.extend(f.commonParams(),{batch:window.JSON.stringify(g)}),opts:{jsonp:!1,fn:function(a){d(a,h)}}})}}(),single:function(b,e,g){b=a(b,e,g);return c(b)}})}(),addEventListener:function(a,
b){this.fire(a,b)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var g=a.open("",c);g.focus();return g}},c=function(a){var c=a.previousSibling,g=a.nextSibling,h=["",a.textContent,""],m=function(a,b){for(var c=a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},k=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),
a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==h[1]&&(h[0]=c&&3===c.nodeType?m(c,"previous"):"",h[2]=g&&3===g.nodeType?m(g,"next"):"",h=k.apply(this,h),""!==h[0]&&""!==h[2]&&(h[0]=h[0].split(" ").reverse().slice(0,10+(" "===h[0].substr(h[0].length-1,1)?1:0)).reverse().join(" "),h[2]=h[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,
before:h[0],after:h[2],txt:h[1],loc:location.href,out:b.getActualHref(a),v:2},f.log("info",b.toQuery(a))))};return function(d,e){var g,h,f,l,n=b.context(d)||window;e=d.target||e;e=!e||e===n.name||"_top"===e&&n.top===n||"_parent"===e&&n.parent===n?"_self":e;f=a(n,e);if("_self"!==e&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))l="go";else try{if(void 0===f.document)throw!0;l="jsonp"}catch(p){l="go"}g=b.destructing(b.bind(function(){k.time_click&&arguments.length&&this.logTime("clk");
var a=b.toArray(arguments);a.unshift(d,f,e);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof d?d:b.getActualHref(d));if("string"===typeof d&&(d=b.createA(d,e),!this.processLink(d))||!k.enabled)return g();h=this.clickParams(d,l);this.logTime();k.log_context&&c(d);if("go"===l)this.redirect(this.api.now("click",h,{"return":!0}),n,f,e);else if(f===n)this.api.now("click",h,{fn:g,timeout:k.click_timeout});else{if(b.contextIsAncestor(n,f))return this.redirect(b.getActualHref(d),
n,f,e);g=b.exceptionLogger(g);setTimeout(function(){g()},k.click_timeout);f.document.open();f.callback=g;f.document.write("<html><head><title>"+b.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api.now("click",h,{fn:"callback","return":!0})+'">\x3c/script></head></html>');f.document.close()}}}(),clickParams:function(a,c){var d=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:k.reaffiliate||null,title:window.document.title,txt:a.innerHTML});
128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},commonParams:function(a){var c={drKey:k.key?null:k.dr_key,key:k.key,libId:k.library_id};("click"===a||"ping"===a)&&b.extend(c,{cuid:k.cuid,loc:location.href,subId:k.sub_id,v:1},c);return c},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,b){function c(a,b){0==k||1E3<b?a(0==k&&f):setTimeout(function(){c(a,2*b)},2*b)}function h(){--k||(f=!l&&p)}var f=
!1,k=2,l=!1,p=!1;if("function"==typeof b){a+="?ch=*&rn=*";var u=11*Math.random(),t=new Image;t.onload=h;t.onerror=function(){l=!0;h()};t.src=a.replace(/\*/,1).replace(/\*/,u);t=new Image;t.onload=h;t.onerror=function(){p=!0;h()};t.src=a.replace(/\*/,2).replace(/\*/,u);c(b,250)}}}}catch(c){a={detect:function(a,b){b(!0)}}}return function(c){var e=b.updateUrl(k.asset_url,{pathname:"/images/pixel.gif"});a.detect(e,c)}}(),enabled:function(){if(k.enabled&&p!==window&&window.vglnk&&(window.vglnk.key||"function"===
typeof window.vglnk))k.enabled=!1;return k.enabled},expose:function(a,c){if(c=c||this[a])"function"===typeof c?c=b.exceptionLogger(b.bind(c,this)):"object"===typeof c&&(c=b.clone(c)),s[a]||(s[a]=c)},fire:function(){var a={};return function(c,d){c=c.toLowerCase();var e=a[c]||{fired:!1,listeners:[]};"function"===typeof d?e.fired?setTimeout(function(){d({type:c})},0):e.listeners.push(d):(e.fired=!0,b.each(e.listeners,function(a){"function"===typeof a&&a({type:c})}),e.listeners=[]);a[c]=e}}(),handleRightClick:function(a,
c){if(k.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.exceptionLogger(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=b.cache(a,"href"),b.cache(a,"href",null)}},harmony:function(){b.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};return function(a){return k.harmony_level<=a}}(),init:b.exceptionLogger(function(){return function(){var a=
!0===window.document.__v5k;window.document.__v5k=!0;a||(this.initLibEvents(),this.initNamespace(),this.initOptions(),b.exceptionLogger(b.bind(this.logException,this),!k.dev),this.initProcessors(),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),this.ping()))}}()),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);s=p[l]=b.noop;this.expose("click");this.expose("link",b.bind(function(a){"element"===b.type(a)&&
a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return f.registerProcessor.apply(f,arguments)});b.extend(s,s===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),initDRApi:function(){var a=
!1;window.DrivingRevenue=b.exceptionLogger(b.destructing(b.bind(function(){a=!0;k.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var c={left:f.onClick,right:f.onContextmenu},d={left:b.noop,right:b.noop},e=b.traits.windowLevelHandlers?a:a.document,g=function(e){e=e||a.event;if((e=b.eventLink(e))&&!b.cache(e,"evented"))h(e,f.harmony(b.harmony.LINK_LEVEL_EVENTS)?
c:d),b.cache(e,"evented",!0)},h=function(a,c){b.on(a,"click",b.bind(c.left,f));b.on(a,"contextmenu",b.bind(c.right,f))};b.on(e,"copy",b.bind(f.onCopy,f));b.on(e,"mousedown",g);if(f.harmony(b.harmony.LINK_LEVEL_EVENTS))b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",g)})});(!b.traits.quirksMode||f.harmony(b.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&h(e,c)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",
vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(s[b[a]]=window[a],"vglnk_domain"===a&&(s[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){k.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(f);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){b.each(b.toArray(a.document.links),b.bind(this.processLink,this))},this);void 0===a?b.each(this.initContext(),
c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(l="vglnk");var a=window,b=l.split("."),d;for(l=b.pop();0<b.length;)d=b.shift(),a[d]=a[d]||{},a=a[d];p=a;s=p[l]=p[l]||{}},initOptions:function(){var a;this.initLegacyOptions();k=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,commercial:null,harmony_level:0,rewrite_modified:!1,
rewrite_original:!0}),k,s,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{},partner_integration:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in k)"_plugin"===a.substr(-7)&&delete k[a]},initPlugins:function(){var a,c=1,d={},e={link_affiliation:"convert",link_optimization:"optimize",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},g=function(b){return function(b){return function(){delete d[b].opts.mode;
c=1;clearTimeout(a);h()}}(b)},h=function(){var e=!1,g={},m=function(a){return function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);f.log.apply(this,c)}}};a=null;b.each(d,function(a,c){a.setup=a.setup||window.vglnk&&window.vglnk[c+"_plugin"];a.setup?(!a.run&&"function"===b.type(a.setup)&&(a.run=a.setup(a.opts,b.clone(b),s,m(a.opts.key||k.key))||b.noop),a.opts.mode===f.PLUGIN_MANUAL?g[c]=a:a.run()):(e=!0,g[c]=a)});d=g;e&&(a=setTimeout(b.exceptionLogger(h),Math.min(Math.max(Math.pow(2,++c),
100),5E3)))},m=function(){setTimeout(function(){f.api.flush()},100);h();b.on("DOMReady",function(){setTimeout(f.api.flush,0)})};return function(a){b.each(a,b.bind(function(a,b){b=e[b]||b;"object"===typeof a&&!1!==a.enabled&&(d[b]={opts:a},a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+b,g(b)))},this));m()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(k.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=
b.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){k.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["norewrite",
"noskim"],custom:function(c){var e,g="";try{e=c.hostname,g=c.protocol,e.charAt(0)}catch(h){return!0}""!==e&&(e=b.canonicalizeHostname(c));return""===e||a===e||"object"===b.type(k.commercial)&&!k.commercial[e]||!g.match(/^https?:$/i)||k.norewrite[e]||!(k.rewrite_original||b.cache(c,"type"))}});return function(a){return c(a,{ancestors:!1})}}(),log:function(a,c,d,e){var g,h=b.toQuery({libId:k.library_id,nocache:b.uniqid()});g="pixel.gif";if("custom"===a)h+="&"+b.toQuery({key:c,type:d}),b.each("array"===
b.type(e)?e:[e],function(a){b.each(["e","i","o"],function(b){delete a[b]});h+="&"+b.toQuery(a)});else{h+="&"+b.toQuery({key:k.key,drKey:k.key?null:k.dr_key});if("time"===a)g="time.gif",a={time:d,type:c};else if("exception"===a)a={e:c,o:d};else if("info"===a)a={i:c};else return;h+="&"+b.toQuery(a)}g=k.api_url+"/"+g+"?"+h;b.transmitsPII(g)||(b.createEl("img").src=g)},logException:function(a){if(k.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?
c.message=a:c=b.extend(c,a);this.log("exception",a,b.toQuery(c))}},logTime:function(){var a;return function(b){0===arguments.length?a=(new Date).getTime():this.log("time",b,(new Date).getTime()-a)}}(),onApiClick:function(a,c,d,e,g){var h=e||b.getActualHref(a),f=b.bind(function(){this.redirect(h,b.context(a),c,d)},this);"object"===typeof g&&(g.tracking||g.image)?(e=b.createEl(g.tracking?"iframe":"img",{src:g.tracking||g.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),setTimeout(b.exceptionLogger(f),
g.timeout||k.hop_timeout)):f()},onApiPing:function(a,c,d,e,g,h){k.rewrite_original=!1;g=b.reformatKeys(g||{});var m,l;e=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,d);return c};l=b.extend(k.plugins,g.plugins);k=b.extend(k,g);delete k.plugins;k.library_id=a;k.click_timeout=c;k.time_ping&&this.logTime("png");"array"===b.type(k.testing_js)&&0<k.testing_js.length&&b.each(k.testing_js,function(a){b.jsonp(a)});b.extend(k.norewrite,e(d));b.extend(k.nofollow,
e(h));for(m in k)"on"===m.toLowerCase().substr(0,2)&&(2<m.length&&"function"===b.type(k[m]))&&(b.on(f,m.toLowerCase().substr(2),b.bind(k[m],window)),delete k[m]);this.initPlugins(l);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;var c=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,d=a.which&&1===a.which||0===a.button,e=b.eventLink(a);if(e&&this.isRewritable(e)&&!c&&d&&!b.isDefaultPrevented(a))return this.click(e),b.preventDefault(a)},onContextmenu:function(a){(a=
b.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(a){var c,d,e,g=[];if(window.getSelection){d=window.getSelection();a=0;for(c=d.rangeCount;a<c;a++){try{e=d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(h){}0<e.length&&128>=e.length&&g.push(e)}}b.each(g,function(a){f.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(k[a]=
b);return k[a]},ping:function(){var a=!1;return function(){if(!a&&(k.key||k.dr_key)){var c={ref:document.referrer||null};a=!0;b.transmitsPII(this.api.now("ping",c,{"return":!0}))||(this.logTime(),this.detectFiltering(b.bind(function(a){a&&(c.type=this.TYPE_ACCEPTABLE);this.api.now("ping",c,{fn:b.bind(this.onApiPing,this)})},this)))}}}(),processLink:function(a){if(this.isRewritable(a)){var c=b.cache(a,"processors")||{};b.each(this.registerProcessor(),function(b){c[b.id]||b.fn(a);c[b.id]=!0});b.cache(a,
"processors",c);return a}},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,d,e){!b.traits.crossWindowCommunication&&!d?(e=c.open(a,e),e.focus()):b.traits.jsRedirectSetsReferrer?setTimeout(b.exceptionLogger(function(){!d||d===c?c.location=a:b.contextIsAncestor(c,d)?d.location=a:d.location.replace(a)}),0):("_blank"===e&&(e=b.uniqid("win_")),e=b.createA(a,e),e.rel="norewrite",c.document.body.appendChild(e),e.click(),e.parentNode.removeChild(e))},
registerProcessor:function(){var a=!1,c=[],d=function(d){if(void 0===d)return c;"function"===b.type(d)&&(c.push({id:b.uniqid(),fn:d}),a&&this.initLinks())};d(function(){a=!0});return d}()};f.init();try{delete window.vglnk_self}catch(u){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(l,f,b){var r={},k;l=f.extend({any:!0},l);k={getDomains:function(){var l=[];f.each(r,function(b,f){l.push(f)});0<l.length&&b.api("domains",{domains:l.join("|")},{fn:f.bind(k.onDomainApi,k)})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,f.on("DOMReady",f.bind(this.getDomains,this)))}}(),onDomainApi:function(k){var l;"object"===f.type(k)&&"array"===f.type(k.results)&&(l={},f.each(k.results,function(b){l[b]=!0}),b.opt("commercial",l))},saveDomain:function(b){b=
f.canonicalizeHostname(b);r[b]=!0},setup:function(){b.opt("rewrite_original",!0);l.any||b.registerProcessor(function(b){k.initDomainLookup();k.saveDomain(b)})}};return function(){k.setup()}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(l,f,b){return function(){b.opt("rewrite_modified",!0)}};window.vglnk=window.vglnk||{};
window.vglnk.partners_plugin=function(l,f){var b="https:"===document.location.protocol,r={setup:function(){window._comscore=window._comscore||[]},run:function(){var k=window._comscore;k&&"function"===f.type(k.push)&&(k.push({c1:8,c2:17570528,c3:1}),f.jsonp("//"+(b?"sb":"b")+".scorecardresearch.com/beacon.js"))}};r.setup();return function(){r.run()}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(l,f,b){l=f.extend({key:null},l);var r={init:function(){f.each(this.getDRSearchForms(),function(b){if(!f.cache(b,"evented")){var l=r.getInput(b),s=function(){l.value||f.css(l,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};f.cache(b,"evented",!0);b.onsubmit=null;l.onfocus=null;l.onblur=null;f.on(l,"focus",function(){f.css(l,{"background-image":"none"})});f.on(l,"blur",s);s();f.on(b,"submit",function(f){r.onSubmit(f,b)})}})},
getDRSearchForms:function(){var b=[];f.each(document.getElementsByTagName("form"),function(f){r.getInput(f)&&f.id.match(/^DR-ebay-search(CSS|2)?$/i)&&b.push(f)});return b},getInput:function(b){return b.p||b.q2},onSubmit:function(k,p){k=k||window.event;var s="http://shop.ebay.com/i.html?"+f.toQuery({_nkw:r.getInput(p).value}),s=f.createA(s,"_blank");f.cache(s,"params",{key:l.key});b.click(s);return f.preventDefault(k)}};return function(){l.key&&(r.init(),f.on("DOMReady",f.bind(r.init,r)))}};
window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(l,f,b,r){var k,p={},s=0;l=f.extend({platform:null},l);k={getLinks:function(){var u=f.platforms(l.platform).getPostIDs();b.api("optimize",{pt:l.platform,i:u?u.join("|"):null,u:location.href},{fn:f.bind(k.onOptimizeApi,k)})},log:function(){r("optimize",{ct:s})},onOptimizeApi:function(b){"object"===f.type(b)&&"object"===f.type(b.optLinks)&&(p=b.optLinks,this.optimizeLinks({data:!0}))},optimizeLink:function(){var b=f.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],
custom:function(a,b){if(b)return Boolean(f.cache(a,"type"))}}),a=function(a){var b=a.href,e=a.textContent||a.innerText,g=function(){var b=f.canonicalizeHostname(a);return f.canonicalizeHostname(f.createEl("a",{href:e}))===b},h=function(){var b;return g()?(b=f.fromQuery(a.search),f.find(b,function(a){return a===e})):!1};return{exact:b===e||function(){var a=e.replace(/(\.\.\.|\u2026)$/,"");return a===e?!1:b.substr(0,a.length)===a}()||h(),partial:function(){var b=f.canonicalizeHostname(a);return RegExp("\\b"+
f.escapeRegExp(b)+"\\b","i").test(e)}()||-1!==e.indexOf(b)}};return function(c){var d,e=p[c.href];if(e&&b(c)){d=a(c);if(d.exact){d=e.frdLink||e.optLink;for(var g;g=c.firstChild;)c.removeChild(g);c.appendChild(document.createTextNode(d))}else if(d.partial)return;f.cache(c,"params",{type:"LO",origOutId:e.pcid+":"+e.linkId});c.href=e.optLink;s++}}}(),optimizeLinks:function(){var l={data:!1,timing:!1};return function(a){l=f.extend(l,a);l.timing&&(l.data&&p)&&(b.registerProcessor(f.bind(this.optimizeLink,
k)),setTimeout(function(){k.log()},0))}}(),setup:function(){if(!l.platform||"full"===l.platform)this.getLinks();else f.on("DOMReady",f.bind(this.getLinks,this))}};k.setup();return function(){f.on("DOMReady",function(){k.optimizeLinks({timing:!0})})}};window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(l,f,b){l=f.extend({level:null},l);return function(){var f=parseInt(l.level,10);isFinite(f)&&b.opt("harmony_level",f)}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(l,f,b,r){var k,p,s=null,u={},a,c=0,d=0,e=0,g=0;l=f.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},l);if(l.key)return k=f.platforms(l.platform),p={addPhrasesToMatcher:function(b){var c="";"regexp"===f.type(b)?c=b.source:"array"===f.type(b)&&(c="(?:^|[\\s\"'\\(])("+f.map(b,f.escapeRegExp).join("|")+")(?=\\s|\\W*$|\\W{2})");
""!==c&&(a=RegExp(a?"(?:"+c+"|"+a.source+")":c,"i"))},focusLink:function(a){a.id||(a.id=f.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPhrases:function(){var a=k.getPostIDs();b.api("insert",f.extend(p.getPartnerParams(),{cat:l.cat,mode:l.mode,pt:l.platform,ps:l.product_source,i:a?a.join("|"):null,u:location.href,type:l.type}),{fn:f.bind(p.onInsertApi,p)})},getPartnerParams:function(){var a,c,d=b.opt("partner"),e={};for(a in d)break;if(a)for(c in d[a])e[a+"_"+c]=d[a][c];
return e},initLink:function(a,c,d){if(d=l.link_target||d)a.target=d;a.rel="nofollow";a.href||(a.href=c.url);f.cache(a,"params",{exp:s,key:l.key,mid:c.mid,type:c.type||null});f.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var b={data:l.link_phrases?!1:l.link_urls,timing:!1},k=function(a,b){var c;c=f.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";f.cache(c,"type","inserted");f.cache(c,"phrase",a);l.ui&&(c.title="Link added by VigLink");
p.initLink(c,b);return c},s=function(b,h){for(var n,p,s,r,B=function(a){var b;a=!a||!l.per_phrase||!a.count||a.count<l.per_phrase;b=!l.per_page||c<l.per_page;return a&&b},C=function(a,b){var c,d,e,h,g,k,m,n,p,t,r=function(b){p.parentNode.insertBefore(a,p);p.parentNode.removeChild(p);return b},s=function(a,b,c){a=f.extend({},a);a.x1-=c;a.y1-=c;a.x2+=c;a.y2+=c;return a.x1<b.x2&&a.x2>b.x1&&a.y1<b.y2&&a.y2>b.y1};p=f.createEl("span");a.parentNode.insertBefore(p,a);p.appendChild(a);t=f.geometry(p);if(l.proximity||
l.same_proximity)for(k in u)if((m=u[k].links)&&!(u[k]===b&&!l.same_proximity||u[k]!==b&&!l.proximity)){n=u[k]===b?Math.max(l.same_proximity,l.proximity):l.proximity;c=0;for(d=m.length;c<d;c++){g=m[c].segments;e=0;for(h=g.length;e<h;e++)if(s(g[e].geometry,t,n))return r(!1)}}return r(!0)},z=function(a,b){var c,d,e,h,g={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(d=k.length;c<d;c++)e=k[c],void 0===h||e.offsetTop===h.offsetTop?l.els.push(e):(g.segments.push(l),l={els:[e]}),h=
e;l.geometry=f.geometry.apply(f,l.els);g.segments.push(l);b.links=b.links||[];b.links.push(g);return b};b&&b.data&&(Boolean(s=b.data.match(/^\s+/))||Boolean(s=b.data.match(a)));)p=s[0],r=s.slice(1).join(""),n=u[r.toLowerCase()],p=b.data.indexOf(p)+p.length-r.length,0<p&&(b=b.splitText(p)),p=b.length<=r.length?null:b.splitText(r.length),r&&!n&&(n={url:r.match(/^https?:\/\//i)?r:"http://"+r,type:"U"}),r&&(B(n)&&C(b,n))&&(r=k(r,n),f.cache(r,"unlinked")||("U"===n.type?g++:"L"===n.type.toUpperCase()?d++:
e++,h(r,b),z(r,n),n.count++,c++)),b=p},n=function(b){var c=!1,d=b.parentNode,e=function(a,b){d.insertBefore(a,b);d.removeChild(b)};b.data&&(c=a.test(b.data.replace(/\s+/," ")));c&&s(b,e)},r=f.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return f.matches(a,"a[href]")}}),z=function(a){var b;if(a){if(r(a,{ancestors:!1,self:!0}))for(b=
a.firstChild;b;)a=b.nextSibling,1===b.nodeType?z(b):3===b.nodeType&&n(b),b=a}else f.each(f.select(l.scope),function(a){r(a,{ancestors:!0,self:!1})&&z(a)})};return function(c){b=f.extend(b,c);b.timing&&(b.data&&a)&&(z(),p.log())}}(),loadPhrases:function(a){var b,c,d,e=[];b=0;for(c=a.length;b<c;b++)d=a[b],d.phrase&&d.url&&(d.phrase=d.phrase.toLowerCase(),u[d.phrase]||(e.push(d.phrase),u[d.phrase]={count:u[d.phrase]?u[d.phrase].count:0,phrase:d.phrase,mid:d.mid,url:d.url,type:d.type||""}));0<e.length&&
this.addPhrasesToMatcher(e);this.insertLinks({data:!0})},log:function(){var a,b,f={heavy:[],lite:[]},k=function(a,b){return b.split(",")[0]-a.split(",")[0]};for(a in u)b=parseInt(u[a].count,10),0<b&&(b=[b,a.replace(/\|/g,"%7C")].join(),f["L"===u[a].type.toUpperCase()?"lite":"heavy"].push(b));f.lite.sort(k);f.heavy.sort(k);r("insert",[{ct:c,cl:d,ch:e,cu:g,exp:s},{pl:f.lite.join("|")},{ph:f.heavy.join("|")}])},onInsertApi:function(a){"object"===f.type(a)&&(s=a.exp,a.results&&this.loadPhrases(a.results))},
setup:function(){l.scope=l.scope||k.scope||"body";l.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))","i"));if(l.link_phrases)if(!l.platform||"full"===l.platform)this.getPhrases();else f.on("DOMReady",f.bind(this.getPhrases,
this))}},p.setup(),function(){f.on("DOMReady",function(){p.insertLinks({timing:!0})})}};window.vglnk=window.vglnk||{};window.vglnk.spotlight_plugin=function(l,f,b){window.vglnk.spotlight_plugin.exports={$:f,opts:l,vglnk:b};return function(){(!f.browser.ie||6<f.browser.version)&&f.jsonp(b.opt("asset_url")+"/spotlight.js")}};
